### ISSUE TITLE
Maybe obvious, but is this supposed to work with a 5WG1117-2A Bus-coupler?

### ISSUE THREAD

**Issue by raphael303** [fxmike08/custom-esphome#4]
Thank you for this component.

I guess I can make it work with the examples given, software wise. But hardware wise I didn't find any info at all. So I guess this is just supposed to work with a Siemens 5WG1117-2A just as it would be used on an Arduino. Right?

If so. Does the 5WG1117-2A have enough power to power an ESP32 via the 5V output? Any experience on that?

Best wishes
Raphael

**Comment by fxmike08** [comment]
Hi Raphael,

Yes, I've tested this solution with 5WG1117-2A. Regarding powering ESP32 using 5WG1117-2A will not work. The KNX protocol specify that each KNX hardware component should now exceed 10mA power consumption, and in this case ESP32 is power hungry with a peak of 250 mA.  My  response to this specific topic [here ](https://github.com/esphome/feature-requests/issues/307#issuecomment-2120879889).

**DO NOT** connect directly 5WG1117-2A to ESP32 on serial, but instead use a level shifter as Siemens for Rx & TX is 5V and ESP32 is 3.3V. My  response to this specific topic [here](https://github.com/esphome/feature-requests/issues/307#issuecomment-1581135552).

Let me know if is still something unclear after reading my comments on [this](https://github.com/esphome/feature-requests/issues/307) thread.  

Best regards,
Mihaita D.

**Comment by raphael303** [comment]
Thank you very much!
Ok, so I get it. 
Level Shifter, inconvenient, but can do. 
Power externally, alright, I didn't think about power. I had arduinos connected there, no problem. But yea. ESPs... that is a different thing. Pitty is only that I rarely have power, where I have KNX in our house. I once tried to steal power directly from KNX with a DCDC converter... didn't work. KNX bus was erratic. 
So, I'll have to see how I can do this, or if at all. Thank you!

**Comment by fxmike08** [comment]
If you have a KNX cable with 4 wires, two used by KNX bus and another two free you could try this:

- Check what is your maximum cable length, and calculate the voltage drop depending on that.
- Depending on how you power the ESP32, you could power it with 5V or 3.3V
- assuming you power ESP32 with 5V
- For example apply 9V (tweak based on the voltage drop) on the two free wires, and then with a voltage regulator (choose &check that based on the datasheet to match with your Voltages) convert it to 5V, and then power the ESP32 with the output.


This solution may add some noise to the KNX bus, but I'm pretty sure it will work with no problem. I'm saying this because on their [specification](https://www.knx.fi/doc/esitteet/KNX-Basics_en.pdf#page=16)  Figure 29. for the live wire 230V they say :

>  \>= 4 mm clearance space or additional insulation

Let me know if this "solve" your problem :grinning:.

Best regards,
Mihaita D.
